// Stubbed package
export const AnyError = class extends Error {};
export const isSystemError = () => false;
export const download = async () => {};
export const getDownloadBaseOptions = () => ({});
export const onDownloadSingle = () => {};
export const createMultiplayer = () => ({});
export const listen = () => {};
export const Tracker = {};
export const applyInstanceChanges = () => {};

export const isWindowsReservedName = {} as any;
export const duplicateInstance = {} as any;
export const InstanceSchema = {} as any;
export const computeInstanceEditChanges = {} as any;
export const createInstance = {} as any;
export const InstanceFileOperationHandler = {} as any;
export const InstanceInstallLock = {} as any;
export const InstanceLockSchema = {} as any;
export const computeFileUpdates = {} as any;
export const ServerFSExporter = {} as any;
export const ServerSSHExporter = {} as any;
export const parseInstanceFiles = {} as any;
export const parseLauncherData = {} as any;
export const generateInstanceManifest = {} as any;
export const getInstanceFiles = {} as any;
export const getInstanceConfigFromCurseforgeModpack = {} as any;
export const getInstanceConfigFromMcbbsModpack = {} as any;
export const getInstanceConfigFromMmcModpack = {} as any;
export const getInstanceConfigFromModrinthModpack = {} as any;
export const getCurseforgeModpackFromInstance = {} as any;
export const getModrinthModpackFromInstance = {} as any;