// Stubbed package
export const AnyError = class extends Error {};
export const isSystemError = () => false;
export const download = async () => {};
export const getDownloadBaseOptions = () => ({});
export const onDownloadSingle = () => {};
export const createMultiplayer = () => ({});
export const listen = () => {};
export const Tracker = {};

export const onProgress = {} as any;
export const DEFAULT_RUNTIME_ALL_URL = {} as any;
export const selectZuluJRE = {} as any;
export const installJavaRuntimeWithJson = {} as any;
export const parseJavaVersion = {} as any;
export const resolveJava = {} as any;
export const scanLocalJava = {} as any;
export const completeInstallation = {} as any;
export const DEFAULT_FORGE_MAVEN = {} as any;
export const DEFAULT_RESOURCE_ROOT_URL = {} as any;
export const installAssets = {} as any;
export const installByProfile = {} as any;
export const InstallError = {} as any;
export const installFabric = {} as any;
export const installForge = {} as any;
export const installLabyMod4 = {} as any;
export const installLibraries = {} as any;
export const installMinecraft = {} as any;
export const installMinecraftJar = {} as any;
export const installNeoForge = {} as any;
export const installOptifine = {} as any;
export const installQuiltVersion = {} as any;
export const installResolvedAssets = {} as any;
export const installResolvedLibraries = {} as any;
export const PostProcessFailedError = {} as any;
export const onDownloadMultiple = {} as any;
export const diagnoseFile = {} as any;